package com.curves.franchise.web;

import com.curves.franchise.domain.Ca;
import com.curves.franchise.domain.Club;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;

import java.util.List;

public class ExportUtil {
    public static void fillCaSheet(Club club, List<Ca> cas, Workbook wb) {
        for (Ca ca : cas) {
            Sheet sh = wb.cloneSheet(2);
            wb.setSheetName(wb.getNumberOfSheets()-1, ca.getCaYear() + "-" + (ca.getCaMonth() + 1));
            Row row = sh.getRow(0);
            row.getCell(2).setCellValue(club.getName());
            row = sh.getRow(1);
            row.getCell(2).setCellValue(club.getOwner());
            row.getCell(7).setCellValue(club.getManager());
            sh.getRow(4).getCell(9).setCellValue(ca.getGoalsTm());
            sh.getRow(4).getCell(10).setCellValue(ca.getThisPlan());
            sh.getRow(5).getCell(9).setCellValue(ca.getGoalsLastTm());
            sh.getRow(6).getCell(9).setCellValue(ca.getGoalsLastActive());
            sh.getRow(7).getCell(9).setCellValue(ca.getGoalsLastShowRatio());
            sh.getRow(8).getCell(9).setCellValue(ca.getGoalsLastSalesRatio());
            sh.getRow(9).getCell(9).setCellValue(ca.getGoalsExitsRatio());
            row = sh.getRow(13);
            row.getCell(4).setCellValue(ca.getSvcTm1());
            row.getCell(5).setCellValue(ca.getSvcTm2());
            row.getCell(6).setCellValue(ca.getSvcTm3());
            row.getCell(7).setCellValue(ca.getSvcTm4());
            row.getCell(8).setCellValue(ca.getSvcTm5());
            row.getCell(9).setCellValue(ca.getSvcTm6());
            row = sh.getRow(14);
            row.getCell(4).setCellValue(ca.getSvcShiftOut1());
            row.getCell(5).setCellValue(ca.getSvcShiftOut2());
            row.getCell(6).setCellValue(ca.getSvcShiftOut3());
            row.getCell(7).setCellValue(ca.getSvcShiftOut4());
            row.getCell(8).setCellValue(ca.getSvcShiftOut5());
            row.getCell(9).setCellValue(ca.getSvcShiftOut6());
            row = sh.getRow(15);
            row.getCell(4).setCellValue(ca.getSvcShiftIn1());
            row.getCell(5).setCellValue(ca.getSvcShiftIn2());
            row.getCell(6).setCellValue(ca.getSvcShiftIn3());
            row.getCell(7).setCellValue(ca.getSvcShiftIn4());
            row.getCell(8).setCellValue(ca.getSvcShiftIn5());
            row.getCell(9).setCellValue(ca.getSvcShiftIn6());
            row = sh.getRow(16);
            row.getCell(4).setCellValue(ca.getSvcHold1());
            row.getCell(5).setCellValue(ca.getSvcHold2());
            row.getCell(6).setCellValue(ca.getSvcHold3());
            row.getCell(7).setCellValue(ca.getSvcHold4());
            row.getCell(8).setCellValue(ca.getSvcHold5());
            row.getCell(9).setCellValue(ca.getSvcHold6());
            row = sh.getRow(17);
            row.getCell(4).setCellValue(ca.getSvcActive1());
            row.getCell(5).setCellValue(ca.getSvcActive2());
            row.getCell(6).setCellValue(ca.getSvcActive3());
            row.getCell(7).setCellValue(ca.getSvcActive4());
            row.getCell(8).setCellValue(ca.getSvcActive5());
            row.getCell(9).setCellValue(ca.getSvcActive6());
            row = sh.getRow(19);
            row.getCell(4).setCellValue(ca.getSvcTotalWo1());
            row.getCell(5).setCellValue(ca.getSvcTotalWo2());
            row.getCell(6).setCellValue(ca.getSvcTotalWo3());
            row.getCell(7).setCellValue(ca.getSvcTotalWo4());
            row.getCell(8).setCellValue(ca.getSvcTotalWo5());
            row = sh.getRow(21);
            row.getCell(4).setCellValue(ca.getSvcMaxWo1());
            row.getCell(5).setCellValue(ca.getSvcMaxWo2());
            row.getCell(6).setCellValue(ca.getSvcMaxWo3());
            row.getCell(7).setCellValue(ca.getSvcMaxWo4());
            row.getCell(8).setCellValue(ca.getSvcMaxWo5());
            row = sh.getRow(22);
            row.getCell(4).setCellValue(ca.getSvcExits1());
            row.getCell(5).setCellValue(ca.getSvcExits2());
            row.getCell(6).setCellValue(ca.getSvcExits3());
            row.getCell(7).setCellValue(ca.getSvcExits4());
            row.getCell(8).setCellValue(ca.getSvcExits5());
            row = sh.getRow(24);
            row.getCell(4).setCellValue(ca.getSvcMeasure1());
            row.getCell(5).setCellValue(ca.getSvcMeasure2());
            row.getCell(6).setCellValue(ca.getSvcMeasure3());
            row.getCell(7).setCellValue(ca.getSvcMeasure4());
            row.getCell(8).setCellValue(ca.getSvcMeasure5());
            sh.getRow(26).getCell(8).setCellValue(ca.getSvc12_5());
            sh.getRow(27).getCell(8).setCellValue(ca.getSvc8to11_5());
            sh.getRow(28).getCell(8).setCellValue(ca.getSvc4to7_5());
            sh.getRow(29).getCell(8).setCellValue(ca.getSvc1to3_5());
            sh.getRow(30).getCell(8).setCellValue(ca.getSvc0_5());
            row = sh.getRow(31);
            row.getCell(4).setCellValue(ca.getSvc3More1());
            row.getCell(5).setCellValue(ca.getSvc3More2());
            row.getCell(6).setCellValue(ca.getSvc3More3());
            row.getCell(7).setCellValue(ca.getSvc3More4());
            row.getCell(8).setCellValue(ca.getSvc3More5());
            row = sh.getRow(32);
            row.getCell(4).setCellValue(ca.getSvcInactive1());
            row.getCell(5).setCellValue(ca.getSvcInactive2());
            row.getCell(6).setCellValue(ca.getSvcInactive3());
            row.getCell(7).setCellValue(ca.getSvcInactive4());
            row.getCell(8).setCellValue(ca.getSvcInactive5());
            row = sh.getRow(33);
            row.getCell(4).setCellValue(ca.getSvcFwoReview1());
            row.getCell(5).setCellValue(ca.getSvcFwoReview2());
            row.getCell(6).setCellValue(ca.getSvcFwoReview3());
            row.getCell(7).setCellValue(ca.getSvcFwoReview4());
            row.getCell(8).setCellValue(ca.getSvcFwoReview5());
            row = sh.getRow(34);
            row.getCell(4).setCellValue(ca.getSvcInterview1());
            row.getCell(5).setCellValue(ca.getSvcInterview2());
            row.getCell(6).setCellValue(ca.getSvcInterview3());
            row.getCell(7).setCellValue(ca.getSvcInterview4());
            row.getCell(8).setCellValue(ca.getSvcInterview5());
            row = sh.getRow(35);
            row.getCell(4).setCellValue(ca.getSvcThanks1());
            row.getCell(5).setCellValue(ca.getSvcThanks2());
            row.getCell(6).setCellValue(ca.getSvcThanks3());
            row.getCell(7).setCellValue(ca.getSvcThanks4());
            row.getCell(8).setCellValue(ca.getSvcThanks5());
            row = sh.getRow(36);
            row.getCell(4).setCellValue(ca.getSvc3C1());
            row.getCell(5).setCellValue(ca.getSvc3C2());
            row.getCell(6).setCellValue(ca.getSvc3C3());
            row.getCell(7).setCellValue(ca.getSvc3C4());
            row.getCell(8).setCellValue(ca.getSvc3C5());
            row = sh.getRow(37);
            row.getCell(4).setCellValue(ca.getSvcReward1());
            row.getCell(5).setCellValue(ca.getSvcReward2());
            row.getCell(6).setCellValue(ca.getSvcReward3());
            row.getCell(7).setCellValue(ca.getSvcReward4());
            row.getCell(8).setCellValue(ca.getSvcReward5());
            row = sh.getRow(38);
            row.getCell(4).setCellValue(ca.getSvcLoyal1());
            row.getCell(5).setCellValue(ca.getSvcLoyal2());
            row.getCell(6).setCellValue(ca.getSvcLoyal3());
            row.getCell(7).setCellValue(ca.getSvcLoyal4());
            row.getCell(8).setCellValue(ca.getSvcLoyal5());
            row = sh.getRow(41);
            row.getCell(4).setCellValue(ca.getCmPostFlyer1());
            row.getCell(5).setCellValue(ca.getCmPostFlyer2());
            row.getCell(6).setCellValue(ca.getCmPostFlyer3());
            row.getCell(7).setCellValue(ca.getCmPostFlyer4());
            row.getCell(8).setCellValue(ca.getCmPostFlyer5());
            row = sh.getRow(42);
            row.getCell(4).setCellValue(ca.getCmHandFlyer1());
            row.getCell(5).setCellValue(ca.getCmHandFlyer2());
            row.getCell(6).setCellValue(ca.getCmHandFlyer3());
            row.getCell(7).setCellValue(ca.getCmHandFlyer4());
            row.getCell(8).setCellValue(ca.getCmHandFlyer5());
            row = sh.getRow(43);
            row.getCell(4).setCellValue(ca.getCmHandFlyerHours1());
            row.getCell(5).setCellValue(ca.getCmHandFlyerHours2());
            row.getCell(6).setCellValue(ca.getCmHandFlyerHours3());
            row.getCell(7).setCellValue(ca.getCmHandFlyerHours4());
            row.getCell(8).setCellValue(ca.getCmHandFlyerHours5());
            row = sh.getRow(44);
            row.getCell(4).setCellValue(ca.getCmOutGpHours1());
            row.getCell(5).setCellValue(ca.getCmOutGpHours2());
            row.getCell(6).setCellValue(ca.getCmOutGpHours3());
            row.getCell(7).setCellValue(ca.getCmOutGpHours4());
            row.getCell(8).setCellValue(ca.getCmOutGpHours5());
            row = sh.getRow(45);
            row.getCell(4).setCellValue(ca.getCmOutGp1());
            row.getCell(5).setCellValue(ca.getCmOutGp2());
            row.getCell(6).setCellValue(ca.getCmOutGp3());
            row.getCell(7).setCellValue(ca.getCmOutGp4());
            row.getCell(8).setCellValue(ca.getCmOutGp5());
            row = sh.getRow(46);
            row.getCell(4).setCellValue(ca.getCmCpBox1());
            row.getCell(5).setCellValue(ca.getCmCpBox2());
            row.getCell(6).setCellValue(ca.getCmCpBox3());
            row.getCell(7).setCellValue(ca.getCmCpBox4());
            row.getCell(8).setCellValue(ca.getCmCpBox5());
            row = sh.getRow(47);
            row.getCell(4).setCellValue(ca.getCmOutGot1());
            row.getCell(5).setCellValue(ca.getCmOutGot2());
            row.getCell(6).setCellValue(ca.getCmOutGot3());
            row.getCell(7).setCellValue(ca.getCmOutGot4());
            row.getCell(8).setCellValue(ca.getCmOutGot5());
            row = sh.getRow(48);
            row.getCell(4).setCellValue(ca.getCmInGot1());
            row.getCell(5).setCellValue(ca.getCmInGot2());
            row.getCell(6).setCellValue(ca.getCmInGot3());
            row.getCell(7).setCellValue(ca.getCmInGot4());
            row.getCell(8).setCellValue(ca.getCmInGot5());
            row = sh.getRow(49);
            row.getCell(4).setCellValue(ca.getCmBlogGot1());
            row.getCell(5).setCellValue(ca.getCmBlogGot2());
            row.getCell(6).setCellValue(ca.getCmBlogGot3());
            row.getCell(7).setCellValue(ca.getCmBlogGot4());
            row.getCell(8).setCellValue(ca.getCmBlogGot5());
            row = sh.getRow(50);
            row.getCell(4).setCellValue(ca.getCmBagGot1());
            row.getCell(5).setCellValue(ca.getCmBagGot2());
            row.getCell(6).setCellValue(ca.getCmBagGot3());
            row.getCell(7).setCellValue(ca.getCmBagGot4());
            row.getCell(8).setCellValue(ca.getCmBagGot5());
            row = sh.getRow(53);
            row.getCell(4).setCellValue(ca.getCmCallIn1());
            row.getCell(5).setCellValue(ca.getCmCallIn2());
            row.getCell(6).setCellValue(ca.getCmCallIn3());
            row.getCell(7).setCellValue(ca.getCmCallIn4());
            row.getCell(8).setCellValue(ca.getCmCallIn5());
            row = sh.getRow(54);
            row.getCell(4).setCellValue(ca.getCmOutGotCall1());
            row.getCell(5).setCellValue(ca.getCmOutGotCall2());
            row.getCell(6).setCellValue(ca.getCmOutGotCall3());
            row.getCell(7).setCellValue(ca.getCmOutGotCall4());
            row.getCell(8).setCellValue(ca.getCmOutGotCall5());
            row = sh.getRow(55);
            row.getCell(4).setCellValue(ca.getCmInGotCall1());
            row.getCell(5).setCellValue(ca.getCmInGotCall2());
            row.getCell(6).setCellValue(ca.getCmInGotCall3());
            row.getCell(7).setCellValue(ca.getCmInGotCall4());
            row.getCell(8).setCellValue(ca.getCmInGotCall5());
            row = sh.getRow(56);
            row.getCell(4).setCellValue(ca.getCmBlogGotCall1());
            row.getCell(5).setCellValue(ca.getCmBlogGotCall2());
            row.getCell(6).setCellValue(ca.getCmBlogGotCall3());
            row.getCell(7).setCellValue(ca.getCmBlogGotCall4());
            row.getCell(8).setCellValue(ca.getCmBlogGotCall5());
            row = sh.getRow(57);
            row.getCell(4).setCellValue(ca.getCmBagGotCall1());
            row.getCell(5).setCellValue(ca.getCmBagGotCall2());
            row.getCell(6).setCellValue(ca.getCmBagGotCall3());
            row.getCell(7).setCellValue(ca.getCmBagGotCall4());
            row.getCell(8).setCellValue(ca.getCmBagGotCall5());
            row = sh.getRow(59);
            row.getCell(4).setCellValue(ca.getCmOwnRefs1());
            row.getCell(5).setCellValue(ca.getCmOwnRefs2());
            row.getCell(6).setCellValue(ca.getCmOwnRefs3());
            row.getCell(7).setCellValue(ca.getCmOwnRefs4());
            row.getCell(8).setCellValue(ca.getCmOwnRefs5());
            row = sh.getRow(60);
            row.getCell(4).setCellValue(ca.getCmOtherRefs1());
            row.getCell(5).setCellValue(ca.getCmOtherRefs2());
            row.getCell(6).setCellValue(ca.getCmOtherRefs3());
            row.getCell(7).setCellValue(ca.getCmOtherRefs4());
            row.getCell(8).setCellValue(ca.getCmOtherRefs5());
            row = sh.getRow(61);
            row.getCell(4).setCellValue(ca.getCmNewspaper1());
            row.getCell(5).setCellValue(ca.getCmNewspaper2());
            row.getCell(6).setCellValue(ca.getCmNewspaper3());
            row.getCell(7).setCellValue(ca.getCmNewspaper4());
            row.getCell(8).setCellValue(ca.getCmNewspaper5());
            row = sh.getRow(62);
            row.getCell(4).setCellValue(ca.getCmTv1());
            row.getCell(5).setCellValue(ca.getCmTv2());
            row.getCell(6).setCellValue(ca.getCmTv3());
            row.getCell(7).setCellValue(ca.getCmTv4());
            row.getCell(8).setCellValue(ca.getCmTv5());
            row = sh.getRow(63);
            row.getCell(4).setCellValue(ca.getCmInternet1());
            row.getCell(5).setCellValue(ca.getCmInternet2());
            row.getCell(6).setCellValue(ca.getCmInternet3());
            row.getCell(7).setCellValue(ca.getCmInternet4());
            row.getCell(8).setCellValue(ca.getCmInternet5());
            row = sh.getRow(64);
            row.getCell(4).setCellValue(ca.getCmSign1());
            row.getCell(5).setCellValue(ca.getCmSign2());
            row.getCell(6).setCellValue(ca.getCmSign3());
            row.getCell(7).setCellValue(ca.getCmSign4());
            row.getCell(8).setCellValue(ca.getCmSign5());
            row = sh.getRow(65);
            row.getCell(4).setCellValue(ca.getCmMate1());
            row.getCell(5).setCellValue(ca.getCmMate2());
            row.getCell(6).setCellValue(ca.getCmMate3());
            row.getCell(7).setCellValue(ca.getCmMate4());
            row.getCell(8).setCellValue(ca.getCmMate5());
            row = sh.getRow(66);
            row.getCell(4).setCellValue(ca.getCmOthers1());
            row.getCell(5).setCellValue(ca.getCmOthers2());
            row.getCell(6).setCellValue(ca.getCmOthers3());
            row.getCell(7).setCellValue(ca.getCmOthers4());
            row.getCell(8).setCellValue(ca.getCmOthers5());
            row = sh.getRow(67);
            row.getCell(4).setCellValue(ca.getCmMailAgpIn1());
            row.getCell(5).setCellValue(ca.getCmMailAgpIn2());
            row.getCell(6).setCellValue(ca.getCmMailAgpIn3());
            row.getCell(7).setCellValue(ca.getCmMailAgpIn4());
            row.getCell(8).setCellValue(ca.getCmMailAgpIn5());
            row = sh.getRow(68);
            row.getCell(4).setCellValue(ca.getCmPostFlyerAgpIn1());
            row.getCell(5).setCellValue(ca.getCmPostFlyerAgpIn2());
            row.getCell(6).setCellValue(ca.getCmPostFlyerAgpIn3());
            row.getCell(7).setCellValue(ca.getCmPostFlyerAgpIn4());
            row.getCell(8).setCellValue(ca.getCmPostFlyerAgpIn5());
            row = sh.getRow(69);
            row.getCell(4).setCellValue(ca.getCmHandFlyerAgpIn1());
            row.getCell(5).setCellValue(ca.getCmHandFlyerAgpIn2());
            row.getCell(6).setCellValue(ca.getCmHandFlyerAgpIn3());
            row.getCell(7).setCellValue(ca.getCmHandFlyerAgpIn4());
            row.getCell(8).setCellValue(ca.getCmHandFlyerAgpIn5());
            row = sh.getRow(70);
            row.getCell(4).setCellValue(ca.getCmCpAgpIn1());
            row.getCell(5).setCellValue(ca.getCmCpAgpIn2());
            row.getCell(6).setCellValue(ca.getCmCpAgpIn3());
            row.getCell(7).setCellValue(ca.getCmCpAgpIn4());
            row.getCell(8).setCellValue(ca.getCmCpAgpIn5());
            row = sh.getRow(71);
            row.getCell(4).setCellValue(ca.getCmOutAgpOut1());
            row.getCell(5).setCellValue(ca.getCmOutAgpOut2());
            row.getCell(6).setCellValue(ca.getCmOutAgpOut3());
            row.getCell(7).setCellValue(ca.getCmOutAgpOut4());
            row.getCell(8).setCellValue(ca.getCmOutAgpOut5());
            row = sh.getRow(72);
            row.getCell(4).setCellValue(ca.getCmInAgpOut1());
            row.getCell(5).setCellValue(ca.getCmInAgpOut2());
            row.getCell(6).setCellValue(ca.getCmInAgpOut3());
            row.getCell(7).setCellValue(ca.getCmInAgpOut4());
            row.getCell(8).setCellValue(ca.getCmInAgpOut5());
            row = sh.getRow(73);
            row.getCell(4).setCellValue(ca.getCmBlogAgpOut1());
            row.getCell(5).setCellValue(ca.getCmBlogAgpOut2());
            row.getCell(6).setCellValue(ca.getCmBlogAgpOut3());
            row.getCell(7).setCellValue(ca.getCmBlogAgpOut4());
            row.getCell(8).setCellValue(ca.getCmBlogAgpOut5());
            row = sh.getRow(74);
            row.getCell(4).setCellValue(ca.getCmBagAgpOut1());
            row.getCell(5).setCellValue(ca.getCmBagAgpOut2());
            row.getCell(6).setCellValue(ca.getCmBagAgpOut3());
            row.getCell(7).setCellValue(ca.getCmBagAgpOut4());
            row.getCell(8).setCellValue(ca.getCmBagAgpOut5());
            row = sh.getRow(82);
            row.getCell(4).setCellValue(ca.getCmFaSum1());
            row.getCell(5).setCellValue(ca.getCmFaSum2());
            row.getCell(6).setCellValue(ca.getCmFaSum3());
            row.getCell(7).setCellValue(ca.getCmFaSum4());
            row.getCell(8).setCellValue(ca.getCmFaSum5());
            row = sh.getRow(84);
            row.getCell(4).setCellValue(ca.getCmTraining1());
            row.getCell(5).setCellValue(ca.getCmTraining2());
            row.getCell(6).setCellValue(ca.getCmTraining3());
            row.getCell(7).setCellValue(ca.getCmTraining4());
            row.getCell(8).setCellValue(ca.getCmTraining5());
            row = sh.getRow(85);
            row.getCell(4).setCellValue(ca.getCmGot3_1());
            row.getCell(5).setCellValue(ca.getCmGot3_2());
            row.getCell(6).setCellValue(ca.getCmGot3_3());
            row.getCell(7).setCellValue(ca.getCmGot3_4());
            row.getCell(8).setCellValue(ca.getCmGot3_5());
            row = sh.getRow(86);
            row.getCell(4).setCellValue(ca.getCmInvitation1());
            row.getCell(5).setCellValue(ca.getCmInvitation2());
            row.getCell(6).setCellValue(ca.getCmInvitation3());
            row.getCell(7).setCellValue(ca.getCmInvitation4());
            row.getCell(8).setCellValue(ca.getCmInvitation5());
            row = sh.getRow(88);
            row.getCell(4).setCellValue(ca.getSalesAch1());
            row.getCell(5).setCellValue(ca.getSalesAch2());
            row.getCell(6).setCellValue(ca.getSalesAch3());
            row.getCell(7).setCellValue(ca.getSalesAch4());
            row.getCell(8).setCellValue(ca.getSalesAch5());
            row = sh.getRow(89);
            row.getCell(4).setCellValue(ca.getSalesMonthly1());
            row.getCell(5).setCellValue(ca.getSalesMonthly2());
            row.getCell(6).setCellValue(ca.getSalesMonthly3());
            row.getCell(7).setCellValue(ca.getSalesMonthly4());
            row.getCell(8).setCellValue(ca.getSalesMonthly5());
            row = sh.getRow(90);
            row.getCell(4).setCellValue(ca.getSalesAllPrepay1());
            row.getCell(5).setCellValue(ca.getSalesAllPrepay2());
            row.getCell(6).setCellValue(ca.getSalesAllPrepay3());
            row.getCell(7).setCellValue(ca.getSalesAllPrepay4());
            row.getCell(8).setCellValue(ca.getSalesAllPrepay5());
            row = sh.getRow(94);
            row.getCell(4).setCellValue(ca.getSalesFaReview1());
            row.getCell(5).setCellValue(ca.getSalesFaReview2());
            row.getCell(6).setCellValue(ca.getSalesFaReview3());
            row.getCell(7).setCellValue(ca.getSalesFaReview4());
            row.getCell(8).setCellValue(ca.getSalesFaReview5());
            row = sh.getRow(95);
            row.getCell(4).setCellValue(ca.getSalesPriceReview1());
            row.getCell(5).setCellValue(ca.getSalesPriceReview2());
            row.getCell(6).setCellValue(ca.getSalesPriceReview3());
            row.getCell(7).setCellValue(ca.getSalesPriceReview4());
            row.getCell(8).setCellValue(ca.getSalesPriceReview5());
            row = sh.getRow(96);
            row.getCell(4).setCellValue(ca.getSalesAck1());
            row.getCell(5).setCellValue(ca.getSalesAck2());
            row.getCell(6).setCellValue(ca.getSalesAck3());
            row.getCell(7).setCellValue(ca.getSalesAck4());
            row.getCell(8).setCellValue(ca.getSalesAck5());
            row = sh.getRow(97);
            row.getCell(4).setCellValue(ca.getSalesTarget1());
            row.getCell(5).setCellValue(ca.getSalesTarget2());
            row.getCell(6).setCellValue(ca.getSalesTarget3());
            row.getCell(7).setCellValue(ca.getSalesTarget4());
            row.getCell(8).setCellValue(ca.getSalesTarget5());
            row = sh.getRow(98);
            row.getCell(4).setCellValue(ca.getSalesMotivation1());
            row.getCell(5).setCellValue(ca.getSalesMotivation2());
            row.getCell(6).setCellValue(ca.getSalesMotivation3());
            row.getCell(7).setCellValue(ca.getSalesMotivation4());
            row.getCell(8).setCellValue(ca.getSalesMotivation5());
            row = sh.getRow(99);
            row.getCell(4).setCellValue(ca.getSalesObstacle1());
            row.getCell(5).setCellValue(ca.getSalesObstacle2());
            row.getCell(6).setCellValue(ca.getSalesObstacle3());
            row.getCell(7).setCellValue(ca.getSalesObstacle4());
            row.getCell(8).setCellValue(ca.getSalesObstacle5());
            sh.getRow(100).getCell(10).setCellValue(ca.getNextPlan());
            row = sh.getRow(101);
            row.getCell(4).setCellValue(ca.getMgmtMeeting1());
            row.getCell(5).setCellValue(ca.getMgmtMeeting2());
            row.getCell(6).setCellValue(ca.getMgmtMeeting3());
            row.getCell(7).setCellValue(ca.getMgmtMeeting4());
            row.getCell(8).setCellValue(ca.getMgmtMeeting5());
            row = sh.getRow(102);
            row.getCell(4).setCellValue(ca.getMgmtCa1());
            row.getCell(5).setCellValue(ca.getMgmtCa2());
            row.getCell(6).setCellValue(ca.getMgmtCa3());
            row.getCell(7).setCellValue(ca.getMgmtCa4());
            row.getCell(8).setCellValue(ca.getMgmtCa5());
            row = sh.getRow(103);
            row.getCell(4).setCellValue(ca.getMgmtGp1());
            row.getCell(5).setCellValue(ca.getMgmtGp2());
            row.getCell(6).setCellValue(ca.getMgmtGp3());
            row.getCell(7).setCellValue(ca.getMgmtGp4());
            row.getCell(8).setCellValue(ca.getMgmtGp5());
            row = sh.getRow(104);
            row.getCell(4).setCellValue(ca.getMgmtLearn1());
            row.getCell(5).setCellValue(ca.getMgmtLearn2());
            row.getCell(6).setCellValue(ca.getMgmtLearn3());
            row.getCell(7).setCellValue(ca.getMgmtLearn4());
            row.getCell(8).setCellValue(ca.getMgmtLearn5());
            row = sh.getRow(105);
            row.getCell(4).setCellValue(ca.getMgmtSheet1());
            row.getCell(5).setCellValue(ca.getMgmtSheet2());
            row.getCell(6).setCellValue(ca.getMgmtSheet3());
            row.getCell(7).setCellValue(ca.getMgmtSheet4());
            row.getCell(8).setCellValue(ca.getMgmtSheet5());
            row = sh.getRow(106);
            row.getCell(4).setCellValue(ca.getMgmtPolicy1());
            row.getCell(5).setCellValue(ca.getMgmtPolicy2());
            row.getCell(6).setCellValue(ca.getMgmtPolicy3());
            row.getCell(7).setCellValue(ca.getMgmtPolicy4());
            row.getCell(8).setCellValue(ca.getMgmtPolicy5());
            row = sh.getRow(107);
            row.getCell(4).setCellValue(ca.getMgmtCompiantSales1());
            row.getCell(5).setCellValue(ca.getMgmtCompiantSales2());
            row.getCell(6).setCellValue(ca.getMgmtCompiantSales3());
            row.getCell(7).setCellValue(ca.getMgmtCompiantSales4());
            row.getCell(8).setCellValue(ca.getMgmtCompiantSales5());
            row = sh.getRow(108);
            row.getCell(4).setCellValue(ca.getMgmtCompiantMethod1());
            row.getCell(5).setCellValue(ca.getMgmtCompiantMethod2());
            row.getCell(6).setCellValue(ca.getMgmtCompiantMethod3());
            row.getCell(7).setCellValue(ca.getMgmtCompiantMethod4());
            row.getCell(8).setCellValue(ca.getMgmtCompiantMethod5());
            row = sh.getRow(109);
            row.getCell(4).setCellValue(ca.getMgmtCompiantProduct1());
            row.getCell(5).setCellValue(ca.getMgmtCompiantProduct2());
            row.getCell(6).setCellValue(ca.getMgmtCompiantProduct3());
            row.getCell(7).setCellValue(ca.getMgmtCompiantProduct4());
            row.getCell(8).setCellValue(ca.getMgmtCompiantProduct5());
            row = sh.getRow(110);
            row.getCell(4).setCellValue(ca.getMgmtCompiantAd1());
            row.getCell(5).setCellValue(ca.getMgmtCompiantAd2());
            row.getCell(6).setCellValue(ca.getMgmtCompiantAd3());
            row.getCell(7).setCellValue(ca.getMgmtCompiantAd4());
            row.getCell(8).setCellValue(ca.getMgmtCompiantAd5());
            row = sh.getRow(111);
            row.getCell(4).setCellValue(ca.getMgmtTraining1());
            row.getCell(5).setCellValue(ca.getMgmtTraining2());
            row.getCell(6).setCellValue(ca.getMgmtTraining3());
            row.getCell(7).setCellValue(ca.getMgmtTraining4());
            row.getCell(8).setCellValue(ca.getMgmtTraining5());
            row = sh.getRow(112);
            row.getCell(4).setCellValue(ca.getMgmtReport1());
            row.getCell(5).setCellValue(ca.getMgmtReport2());
            row.getCell(6).setCellValue(ca.getMgmtReport3());
            row.getCell(7).setCellValue(ca.getMgmtReport4());
            row.getCell(8).setCellValue(ca.getMgmtReport5());
            row = sh.getRow(113);
            row.getCell(4).setCellValue(ca.getMgmtPlan1());
            row.getCell(5).setCellValue(ca.getMgmtPlan2());
            row.getCell(6).setCellValue(ca.getMgmtPlan3());
            row.getCell(7).setCellValue(ca.getMgmtPlan4());
            row.getCell(8).setCellValue(ca.getMgmtPlan5());
            row = sh.getRow(114);
            row.getCell(4).setCellValue(ca.getMgmtMaintain1());
            row.getCell(5).setCellValue(ca.getMgmtMaintain2());
            row.getCell(6).setCellValue(ca.getMgmtMaintain3());
            row.getCell(7).setCellValue(ca.getMgmtMaintain4());
            row.getCell(8).setCellValue(ca.getMgmtMaintain5());
            row = sh.getRow(115);
            row.getCell(4).setCellValue(ca.getMgmtFace2Face1());
            row.getCell(5).setCellValue(ca.getMgmtFace2Face2());
            row.getCell(6).setCellValue(ca.getMgmtFace2Face3());
            row.getCell(7).setCellValue(ca.getMgmtFace2Face4());
            row.getCell(8).setCellValue(ca.getMgmtFace2Face5());
            row = sh.getRow(123);
            row.getCell(0).setCellValue(ca.getStaff1Name());
            row.getCell(4).setCellValue(ca.getStaff1Ach1());
            row.getCell(5).setCellValue(ca.getStaff1Ach2());
            row.getCell(6).setCellValue(ca.getStaff1Ach3());
            row.getCell(7).setCellValue(ca.getStaff1Ach4());
            row.getCell(8).setCellValue(ca.getStaff1Ach5());
            row = sh.getRow(124);
            row.getCell(4).setCellValue(ca.getStaff1Mm1());
            row.getCell(5).setCellValue(ca.getStaff1Mm2());
            row.getCell(6).setCellValue(ca.getStaff1Mm3());
            row.getCell(7).setCellValue(ca.getStaff1Mm4());
            row.getCell(8).setCellValue(ca.getStaff1Mm5());
            row = sh.getRow(125);
            row.getCell(4).setCellValue(ca.getStaff1App1());
            row.getCell(5).setCellValue(ca.getStaff1App2());
            row.getCell(6).setCellValue(ca.getStaff1App3());
            row.getCell(7).setCellValue(ca.getStaff1App4());
            row.getCell(8).setCellValue(ca.getStaff1App5());
            row = sh.getRow(126);
            row.getCell(4).setCellValue(ca.getStaff1Ns1());
            row.getCell(5).setCellValue(ca.getStaff1Ns2());
            row.getCell(6).setCellValue(ca.getStaff1Ns3());
            row.getCell(7).setCellValue(ca.getStaff1Ns4());
            row.getCell(8).setCellValue(ca.getStaff1Ns5());
            row = sh.getRow(127);
            row.getCell(4).setCellValue(ca.getStaff1Lx1());
            row.getCell(5).setCellValue(ca.getStaff1Lx2());
            row.getCell(6).setCellValue(ca.getStaff1Lx3());
            row.getCell(7).setCellValue(ca.getStaff1Lx4());
            row.getCell(8).setCellValue(ca.getStaff1Lx5());
            row = sh.getRow(128);
            row.getCell(0).setCellValue(ca.getStaff2Name());
            row.getCell(4).setCellValue(ca.getStaff2Ach1());
            row.getCell(5).setCellValue(ca.getStaff2Ach2());
            row.getCell(6).setCellValue(ca.getStaff2Ach3());
            row.getCell(7).setCellValue(ca.getStaff2Ach4());
            row.getCell(8).setCellValue(ca.getStaff2Ach5());
            row = sh.getRow(129);
            row.getCell(4).setCellValue(ca.getStaff2Mm1());
            row.getCell(5).setCellValue(ca.getStaff2Mm2());
            row.getCell(6).setCellValue(ca.getStaff2Mm3());
            row.getCell(7).setCellValue(ca.getStaff2Mm4());
            row.getCell(8).setCellValue(ca.getStaff2Mm5());
            row = sh.getRow(130);
            row.getCell(4).setCellValue(ca.getStaff2App1());
            row.getCell(5).setCellValue(ca.getStaff2App2());
            row.getCell(6).setCellValue(ca.getStaff2App3());
            row.getCell(7).setCellValue(ca.getStaff2App4());
            row.getCell(8).setCellValue(ca.getStaff2App5());
            row = sh.getRow(131);
            row.getCell(4).setCellValue(ca.getStaff2Ns1());
            row.getCell(5).setCellValue(ca.getStaff2Ns2());
            row.getCell(6).setCellValue(ca.getStaff2Ns3());
            row.getCell(7).setCellValue(ca.getStaff2Ns4());
            row.getCell(8).setCellValue(ca.getStaff2Ns5());
            row = sh.getRow(132);
            row.getCell(4).setCellValue(ca.getStaff2Lx1());
            row.getCell(5).setCellValue(ca.getStaff2Lx2());
            row.getCell(6).setCellValue(ca.getStaff2Lx3());
            row.getCell(7).setCellValue(ca.getStaff2Lx4());
            row.getCell(8).setCellValue(ca.getStaff2Lx5());
            row = sh.getRow(133);
            row.getCell(0).setCellValue(ca.getStaff3Name());
            row.getCell(4).setCellValue(ca.getStaff3Ach1());
            row.getCell(5).setCellValue(ca.getStaff3Ach2());
            row.getCell(6).setCellValue(ca.getStaff3Ach3());
            row.getCell(7).setCellValue(ca.getStaff3Ach4());
            row.getCell(8).setCellValue(ca.getStaff3Ach5());
            row = sh.getRow(134);
            row.getCell(4).setCellValue(ca.getStaff3Mm1());
            row.getCell(5).setCellValue(ca.getStaff3Mm2());
            row.getCell(6).setCellValue(ca.getStaff3Mm3());
            row.getCell(7).setCellValue(ca.getStaff3Mm4());
            row.getCell(8).setCellValue(ca.getStaff3Mm5());
            row = sh.getRow(135);
            row.getCell(4).setCellValue(ca.getStaff3App1());
            row.getCell(5).setCellValue(ca.getStaff3App2());
            row.getCell(6).setCellValue(ca.getStaff3App3());
            row.getCell(7).setCellValue(ca.getStaff3App4());
            row.getCell(8).setCellValue(ca.getStaff3App5());
            row = sh.getRow(136);
            row.getCell(4).setCellValue(ca.getStaff3Ns1());
            row.getCell(5).setCellValue(ca.getStaff3Ns2());
            row.getCell(6).setCellValue(ca.getStaff3Ns3());
            row.getCell(7).setCellValue(ca.getStaff3Ns4());
            row.getCell(8).setCellValue(ca.getStaff3Ns5());
            row = sh.getRow(137);
            row.getCell(4).setCellValue(ca.getStaff3Lx1());
            row.getCell(5).setCellValue(ca.getStaff3Lx2());
            row.getCell(6).setCellValue(ca.getStaff3Lx3());
            row.getCell(7).setCellValue(ca.getStaff3Lx4());
            row.getCell(8).setCellValue(ca.getStaff3Lx5());
            row = sh.getRow(138);
            row.getCell(0).setCellValue(ca.getStaff4Name());
            row.getCell(4).setCellValue(ca.getStaff4Ach1());
            row.getCell(5).setCellValue(ca.getStaff4Ach2());
            row.getCell(6).setCellValue(ca.getStaff4Ach3());
            row.getCell(7).setCellValue(ca.getStaff4Ach4());
            row.getCell(8).setCellValue(ca.getStaff4Ach5());
            row = sh.getRow(139);
            row.getCell(4).setCellValue(ca.getStaff4Mm1());
            row.getCell(5).setCellValue(ca.getStaff4Mm2());
            row.getCell(6).setCellValue(ca.getStaff4Mm3());
            row.getCell(7).setCellValue(ca.getStaff4Mm4());
            row.getCell(8).setCellValue(ca.getStaff4Mm5());
            row = sh.getRow(140);
            row.getCell(4).setCellValue(ca.getStaff4App1());
            row.getCell(5).setCellValue(ca.getStaff4App2());
            row.getCell(6).setCellValue(ca.getStaff4App3());
            row.getCell(7).setCellValue(ca.getStaff4App4());
            row.getCell(8).setCellValue(ca.getStaff4App5());
            row = sh.getRow(141);
            row.getCell(4).setCellValue(ca.getStaff4Ns1());
            row.getCell(5).setCellValue(ca.getStaff4Ns2());
            row.getCell(6).setCellValue(ca.getStaff4Ns3());
            row.getCell(7).setCellValue(ca.getStaff4Ns4());
            row.getCell(8).setCellValue(ca.getStaff4Ns5());
            row = sh.getRow(142);
            row.getCell(4).setCellValue(ca.getStaff4Lx1());
            row.getCell(5).setCellValue(ca.getStaff4Lx2());
            row.getCell(6).setCellValue(ca.getStaff4Lx3());
            row.getCell(7).setCellValue(ca.getStaff4Lx4());
            row.getCell(8).setCellValue(ca.getStaff4Lx5());
            row = sh.getRow(143);
            row.getCell(0).setCellValue(ca.getStaff5Name());
            row.getCell(4).setCellValue(ca.getStaff5Ach1());
            row.getCell(5).setCellValue(ca.getStaff5Ach2());
            row.getCell(6).setCellValue(ca.getStaff5Ach3());
            row.getCell(7).setCellValue(ca.getStaff5Ach4());
            row.getCell(8).setCellValue(ca.getStaff5Ach5());
            row = sh.getRow(144);
            row.getCell(4).setCellValue(ca.getStaff5Mm1());
            row.getCell(5).setCellValue(ca.getStaff5Mm2());
            row.getCell(6).setCellValue(ca.getStaff5Mm3());
            row.getCell(7).setCellValue(ca.getStaff5Mm4());
            row.getCell(8).setCellValue(ca.getStaff5Mm5());
            row = sh.getRow(145);
            row.getCell(4).setCellValue(ca.getStaff5App1());
            row.getCell(5).setCellValue(ca.getStaff5App2());
            row.getCell(6).setCellValue(ca.getStaff5App3());
            row.getCell(7).setCellValue(ca.getStaff5App4());
            row.getCell(8).setCellValue(ca.getStaff5App5());
            row = sh.getRow(146);
            row.getCell(4).setCellValue(ca.getStaff5Ns1());
            row.getCell(5).setCellValue(ca.getStaff5Ns2());
            row.getCell(6).setCellValue(ca.getStaff5Ns3());
            row.getCell(7).setCellValue(ca.getStaff5Ns4());
            row.getCell(8).setCellValue(ca.getStaff5Ns5());
            row = sh.getRow(147);
            row.getCell(4).setCellValue(ca.getStaff5Lx1());
            row.getCell(5).setCellValue(ca.getStaff5Lx2());
            row.getCell(6).setCellValue(ca.getStaff5Lx3());
            row.getCell(7).setCellValue(ca.getStaff5Lx4());
            row.getCell(8).setCellValue(ca.getStaff5Lx5());
            row = sh.getRow(148);
            row.getCell(0).setCellValue(ca.getStaff6Name());
            row.getCell(4).setCellValue(ca.getStaff6Ach1());
            row.getCell(5).setCellValue(ca.getStaff6Ach2());
            row.getCell(6).setCellValue(ca.getStaff6Ach3());
            row.getCell(7).setCellValue(ca.getStaff6Ach4());
            row.getCell(8).setCellValue(ca.getStaff6Ach5());
            row = sh.getRow(149);
            row.getCell(4).setCellValue(ca.getStaff6Mm1());
            row.getCell(5).setCellValue(ca.getStaff6Mm2());
            row.getCell(6).setCellValue(ca.getStaff6Mm3());
            row.getCell(7).setCellValue(ca.getStaff6Mm4());
            row.getCell(8).setCellValue(ca.getStaff6Mm5());
            row = sh.getRow(150);
            row.getCell(4).setCellValue(ca.getStaff6App1());
            row.getCell(5).setCellValue(ca.getStaff6App2());
            row.getCell(6).setCellValue(ca.getStaff6App3());
            row.getCell(7).setCellValue(ca.getStaff6App4());
            row.getCell(8).setCellValue(ca.getStaff6App5());
            row = sh.getRow(151);
            row.getCell(4).setCellValue(ca.getStaff6Ns1());
            row.getCell(5).setCellValue(ca.getStaff6Ns2());
            row.getCell(6).setCellValue(ca.getStaff6Ns3());
            row.getCell(7).setCellValue(ca.getStaff6Ns4());
            row.getCell(8).setCellValue(ca.getStaff6Ns5());
            row = sh.getRow(152);
            row.getCell(4).setCellValue(ca.getStaff6Lx1());
            row.getCell(5).setCellValue(ca.getStaff6Lx2());
            row.getCell(6).setCellValue(ca.getStaff6Lx3());
            row.getCell(7).setCellValue(ca.getStaff6Lx4());
            row.getCell(8).setCellValue(ca.getStaff6Lx5());
        }
    }
}
